apiVersion: v1
kind: Secret
metadata:
  name: {{ include "levee.secretName" . }}
type: Opaque
stringData:
  h-secret: {{ .Values.hCaptcha.secret }}
  h-site-key: {{ .Values.hCaptcha.siteKey }}
  discord-secret: {{ .Values.discord.clientSecret }}
